version: 1

services:
  - type: web
    name: bingedu-server
    runtime: node
    repo: https://github.com/bingsu1103/BingEdu-BE-Microservice
    branch: main
    envVars:
      - key: PORT
        value: 8080
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    healthCheckPath: /
    rootDir: api-gateway
